/* Created by Phil Malone. 2023.
    This class illustrates my simplified Odometry Strategy.
    It implements basic straight line motions but with heading and drift controls to limit drift.
    See the readme for a link to a video tutorial explaining the operation and limitations of the code.
 */

package org.firstinspires.ftc.teamcode.Decode.Teleop;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.util.ElapsedTime;
import org.firstinspires.ftc.teamcode.dragon.SimplifiedOdometryRobot;
/*
 * This OpMode illustrates a teleop OpMode for an Omni robot.
 * An external "Robot" class is used to manage all motor/sensor interfaces, and to assist driving functions.
 * The IMU gyro is used to stabilize the heading when the operator is not requesting a turn.
 */

@TeleOp(name="spec_partner", group = "shiningdanyang")
public class spec_partner extends LinearOpMode
{
    double P = 50;
    double I = 0.6;
    double D = 0.001;
    double F = 17;
    
    final double SAFE_DRIVE_SPEED   = 0.8 ; // Adjust this to your robot and your driver.  Slower usually means more accuracy.  Max value = 1.0
    final double SAFE_STRAFE_SPEED  = 0.8 ; // Adjust this to your robot and your driver.  Slower usually means more accuracy.  Max value = 1.0
    final double SAFE_YAW_SPEED     = 0.5 ; // Adjust this to your robot and your driver.  Slower usually means more accuracy.  Max value = 1.0
    final double HEADING_HOLD_TIME  = 10.0 ; // How long to hold heading once all driver input stops. (This Avoids effects of Gyro Drift)

    // local parameters
    ElapsedTime stopTime   = new ElapsedTime();  // Use for timeouts.
    boolean autoHeading    = false; // used to indicate when heading should be locked.

    // get an instance of the "Robot" class.
    SimplifiedOdometryRobot robot = new SimplifiedOdometryRobot(this);
    private Servo srvTurret0 = null, srvTurret1 = null;
    private Servo srvLoad = null;
    private Servo srvOval = null;
    private DcMotorEx motorIntake = null;
    private DcMotorEx shooter = null;
    private DcMotorEx shootstraff = null;

    public void srvTurn(Servo servoInstance, double value)
    {
        servoInstance.setPosition(value + 0.5);
    }
    public void moveDrivetrain(double x, double y, double z)
    {
        robot.readSensors();

        // read joystick values and scale according to limits set at top of this file
        double drive  = y;      //  Fwd/back on left stick
        double strafe = -x;     //  Left/Right on left stick
        double yaw    = z;       //  Rotate on right stick

        // This is where we heep the robot heading locked so it doesn't turn while driving or strafing in a straight line.
        // Is the driver turning the robot, or should it hold its heading?
        if (Math.abs(yaw) > 0.05) {
            // driver is commanding robot to turn, so turn off auto heading.
            autoHeading = false;
        } else {
            // If we are not already locked, wait for robot to stop rotating (<2 deg per second) and then lock-in the current heading.
            if (!autoHeading && Math.abs(robot.getTurnRate()) < 2.0) {
                robot.yawController.reset(robot.getHeading());  // Lock in the current heading
                autoHeading = true;
            }
        }

        // If auto heading is on, override manual yaw with the value generated by the heading controller.
        if (autoHeading) {
            yaw = robot.yawController.getOutput(robot.getHeading());
        }

        //  Drive the wheels based on the desired axis motions
        robot.moveRobot(drive, strafe, yaw);

        // If the robot has just been sitting here for a while, make heading setpoint track any gyro drift to prevent rotating.
        if ((drive == 0) && (strafe == 0) && (yaw == 0)) {
            if (stopTime.time() > HEADING_HOLD_TIME) {
                robot.yawController.reset(robot.getHeading());  // just keep tracking the current heading
            }
        } else {
            stopTime.reset();
        }
    }


    @Override public void runOpMode()
    {
        // Initialize the drive hardware & Turn on telemetry
        robot.initialize(true);

        srvTurret0 = hardwareMap.get(Servo.class, "srvTurret0");
        srvTurret1 = hardwareMap.get(Servo.class, "srvTurret1");
        srvLoad = hardwareMap.get(Servo.class, "srvLoad");
        motorIntake = hardwareMap.get(DcMotorEx.class, "drvintake");
        srvOval = hardwareMap.get(Servo.class, "srvOval0");
        shooter = hardwareMap.get(DcMotorEx.class, "drvShoot");
        shootstraff = hardwareMap.get(DcMotorEx.class, "drvShootstraff");
        ElapsedTime waitTimer = new ElapsedTime();

        shooter.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        shooter.setDirection(DcMotorSimple.Direction.REVERSE);
        shooter.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        
        shootstraff.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        shootstraff.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        shooter.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);
        shooter.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);
    
        shootstraff.setVelocityPIDFCoefficients(P, I, D, F);
        shooter.setVelocityPIDFCoefficients(P, I, D, F);

        // Wait for driver to press start
        while(opModeInInit()) {
            telemetry.addData(">", "Touch Play to drive");
            srvTurn(srvTurret0, -0.2);

            // Read and display sensor data
            robot.readSensors();
            // Allow the driver to reset the gyro by pressing both small gamepad buttons
            if(gamepad1.options && gamepad1.share){
                robot.resetHeading();
                robot.resetOdometry();
            }

            // read joystick values and scale according to limits set at top of this file
            double drive  = -gamepad1.left_stick_y * SAFE_DRIVE_SPEED;      //  Fwd/back on left stick
            double strafe = -gamepad1.left_stick_x * SAFE_STRAFE_SPEED;     //  Left/Right on left stick
            double yaw    = -gamepad1.right_stick_x * SAFE_YAW_SPEED;       //  Rotate on right stick

            // This is where we heep the robot heading locked so it doesn't turn while driving or strafing in a straight line.
            // Is the driver turning the robot, or should it hold its heading?
            if (Math.abs(yaw) > 0.05) {
                // driver is commanding robot to turn, so turn off auto heading.
                autoHeading = false;
            } else {
                // If we are not already locked, wait for robot to stop rotating (<2 deg per second) and then lock-in the current heading.
                if (!autoHeading && Math.abs(robot.getTurnRate()) < 2.0) {
                    robot.yawController.reset(robot.getHeading());  // Lock in the current heading
                    autoHeading = true;
                }
            }

            // If auto heading is on, override manual yaw with the value generated by the heading controller.
            if (autoHeading) {
                yaw = robot.yawController.getOutput(robot.getHeading());
            }

            //  Drive the wheels based on the desired axis motions
            robot.moveRobot(drive, strafe, yaw);

            // If the robot has just been sitting here for a while, make heading setpoint track any gyro drift to prevent rotating.
            if ((drive == 0) && (strafe == 0) && (yaw == 0)) {
                if (stopTime.time() > HEADING_HOLD_TIME) {
                    robot.yawController.reset(robot.getHeading());  // just keep tracking the current heading
                }
            } else {
                stopTime.reset();
            }
            telemetry.update();
        };
        srvOval.setPosition(0);
        robot.initialize(true);
        robot.resetHeading();
        robot.resetOdometry();


        // ==== start =====
        srvTurn(srvTurret0, -0.275);
        srvTurn(srvTurret1, -0.275);//left
        srvOval.setPosition(0.1);
        shooter.setVelocity(1150);
        shootstraff.setVelocity(1150);
        sleep(3000);
        motorIntake.setPower(0.5);
        srvLoad.setPosition(0.35);
        
        sleep(3000);
        //shooter.setPower(0.55);
        //shootstraff.setPower(0.55);
        srvLoad.setPosition(0);
        srvOval.setPosition(0.15);
        srvTurn(srvTurret0, -0.26);
        srvTurn(srvTurret1, -0.26);
        motorIntake.setPower(1);//left  
        

        //1
        while(opModeIsActive() && robot.strafeDistance < 23)
        {
            moveDrivetrain(1.0, 0.0, 0.0);
        }

        while(opModeIsActive() && robot.driveDistance < 43)
        {
            moveDrivetrain(0.0, 1, 0.0);
        }
        motorIntake.setPower(0.6);
        while(opModeIsActive() && robot.driveDistance > 15)
        {
            moveDrivetrain(0.0, -1.0, 0.0);
        }
        while(opModeIsActive() && robot.strafeDistance > 15)
        {
            moveDrivetrain(-1.0, 0.0, 0.0);
        }
        srvLoad.setPosition(0.35);
        waitTimer.reset();
        while(waitTimer.seconds() <= 2) robot.moveRobot(0,0,0);
        srvLoad.setPosition(0);
        motorIntake.setPower(1);
        srvTurn(srvTurret0, -0.27);
        srvTurn(srvTurret1, -0.27);
        
        //2
        while(opModeIsActive() && robot.strafeDistance < 60) {
            moveDrivetrain(1, 0.0, 0.0);
        }
        while(opModeIsActive() && robot.driveDistance < 40) {
            moveDrivetrain(0, 0.6, 0.0);
        }
        motorIntake.setPower(0.6);
        while(opModeIsActive() && robot.driveDistance > 0) {
            moveDrivetrain(-0.9, -0.7, 0.0);
        }
        srvLoad.setPosition(0.35);
        waitTimer.reset();
        while(waitTimer.seconds() <= 2.2) robot.moveRobot(0,0,0);
        srvLoad.setPosition(0);
        motorIntake.setPower(1);
        
        while(opModeIsActive() && robot.driveDistance < 43) {
            moveDrivetrain(0, 0.8, 0.0);
        }
        waitTimer.reset();
        while(waitTimer.seconds() <= 1) robot.moveRobot(0,0,0);
        motorIntake.setPower(0.6);
         while(opModeIsActive() && robot.driveDistance > 5) {
            moveDrivetrain(0, -0.8, 0.0);
        }
        srvLoad.setPosition(0.35);
        waitTimer.reset();
        while(waitTimer.seconds() <= 2) robot.moveRobot(0,0,0);
        srvLoad.setPosition(0);
        
        while(opModeIsActive() && robot.driveDistance < 49) {
            moveDrivetrain(-0.1, 0.8, 0);
        }
        waitTimer.reset();
        while(waitTimer.seconds() <= 1) robot.moveRobot(0,0,0);
        motorIntake.setPower(1);
         while(opModeIsActive() && robot.driveDistance > 1) {
            moveDrivetrain(0.1, -0.8, 0);
        }
        srvLoad.setPosition(0.35);
        waitTimer.reset();
        while(waitTimer.seconds() <= 2) robot.moveRobot(0,0,0);
        srvLoad.setPosition(0);
        
        //3
        robot.moveRobot(0,0,0);
        sleep(500);

        // ====== end ======
        while (opModeIsActive())
        {
            robot.readSensors();

            // Allow the driver to reset the gyro by pressing both small gamepad buttons
            if(gamepad1.options && gamepad1.share){
                robot.resetHeading();
                robot.resetOdometry();
            }

            // read joystick values and scale according to limits set at top of this file
            double drive  = -gamepad1.left_stick_y * SAFE_DRIVE_SPEED;      //  Fwd/back on left stick
            double strafe = -gamepad1.left_stick_x * SAFE_STRAFE_SPEED;     //  Left/Right on left stick
            double yaw    = -gamepad1.right_stick_x * SAFE_YAW_SPEED;       //  Rotate on right stick

            // This is where we heep the robot heading locked so it doesn't turn while driving or strafing in a straight line.
            // Is the driver turning the robot, or should it hold its heading?
            if (Math.abs(yaw) > 0.05) {
                // driver is commanding robot to turn, so turn off auto heading.
                autoHeading = false;
            } else {
                // If we are not already locked, wait for robot to stop rotating (<2 deg per second) and then lock-in the current heading.
                if (!autoHeading && Math.abs(robot.getTurnRate()) < 2.0) {
                    robot.yawController.reset(robot.getHeading());  // Lock in the current heading
                    autoHeading = true;
                }
            }

            // If auto heading is on, override manual yaw with the value generated by the heading controller.
            if (autoHeading) {
                yaw = robot.yawController.getOutput(robot.getHeading());
            }

            //  Drive the wheels based on the desired axis motions
            robot.moveRobot(drive, strafe, yaw);

            // If the robot has just been sitting here for a while, make heading setpoint track any gyro drift to prevent rotating.
            if ((drive == 0) && (strafe == 0) && (yaw == 0)) {
                if (stopTime.time() > HEADING_HOLD_TIME) {
                    robot.yawController.reset(robot.getHeading());  // just keep tracking the current heading
                }
            } else {
                stopTime.reset();
            }
        }
    }
}
